// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Interaction Olympics",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Interaction Olympics",
            targets: ["AppModule"],
            bundleIdentifier: "com.phcs.InteractionOlympics",
            teamIdentifier: "LP3UHZ556W",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .camera(purposeString: "The app needs your camera to capture your motion!")
            ],
            additionalInfoPlistContentFilePath: "ExtraInfo.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["ExtraInfo.plist"],
            resources: [
                .process("Resources")
            ]
        )
    ]
)